# Generated by Django 2.1.7 on 2019-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_Service_Number', models.CharField(max_length=120)),
                ('Electric_Meter_Number', models.CharField(max_length=20)),
                ('Quaters_Place', models.CharField(choices=[('SBI', 'SBI'), ('SBH', 'SBH'), ('Andra Bank', 'Andra Bank'), ('ICICI', 'ICICI'), ('HDFC', 'HDFC'), ('CENTRAL BANK', 'CENTRAL BANK'), ('UTI BANK', 'UTI BANK')], max_length=30)),
                ('Quaters_Number', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Secunderabad', 'Secunderabad')], max_length=30)),
                ('Quaters_Type', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Secunderabad', 'Secunderabad')], max_length=30)),
                ('Quaters_Description', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Secunderabad', 'Secunderabad')], max_length=30)),
                ('Quaters_Date', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Secunderabad', 'Secunderabad')], max_length=30)),
            ],
        ),
    ]
