# Generated by Django 2.1.7 on 2019-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Quaters_Date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Quaters_Description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Quaters_Number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Quaters_Place',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Quaters_Type',
            field=models.CharField(max_length=30),
        ),
    ]
