# Generated by Django 2.1.7 on 2019-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0002_auto_20190315_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Contract_Service_Number',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
